language: c++
cache: ccache
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
env:
- ARDUINO_VERSION=1.8.8 ARDUINO_ESP32_VERSION=1.0.1 LIB_HTTPCLIENTESP32EX_VERSION=v1.0.0 ARDUINO_ROOT=${HOME}/arduino-${ARDUINO_VERSION} ARDUINO_ESP32_ROOT=${ARDUINO_ROOT}/hardware/esp32com/esp32 ARDUINO_HOME=${HOME}/Arduino
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
- ( cd ${HOME} && wget https://downloads.arduino.cc/arduino-${ARDUINO_VERSION}-linux64.tar.xz && tar xf arduino-${ARDUINO_VERSION}-linux64.tar.xz )
- ( LIB=HTTPClientESP32Ex VERSION=${LIB_HTTPCLIENTESP32EX_VERSION} && cd ${HOME} && wget https://github.com/mobizt/HTTPClientESP32Ex/archive/${VERSION}.zip -q -O ${LIB}.zip && unzip -q ${LIB}.zip && rm ${LIB}.zip && mv ${LIB}-* ${LIB} )
- git clone --branch ${ARDUINO_ESP32_VERSION} https://github.com/espressif/arduino-esp32.git ${ARDUINO_ESP32_ROOT}
- git submodule init && git submodule update
- ( cd ${ARDUINO_ESP32_ROOT}/tools && python get.py )
before_script:
- mkdir -p ${ARDUINO_HOME}/libraries
- ( cd ${ARDUINO_HOME}/libraries && ln -s ${TRAVIS_BUILD_DIR} firebase-arduino && ln -s ${HOME}/HTTPClientESP32Ex ./)
